# Generated by Django 3.2.9 on 2021-12-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_share', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=1000)),
                ('submit_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
