# Generated by Django 3.2.9 on 2021-12-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_share', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
