# Generated by Django 3.2.9 on 2021-12-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_share', '0005_alter_message_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='title',
        ),
    ]
